# Acceso local desde el contenedor via admin docker
local   all   admin   trust
host    all   admin   0.0.0.0/0   scram-sha-256
# El resto de usuarios que no sean admin se verifica mediante LDAP
# https://www.postgresql.org/docs/current/auth-ldap.html
host    all             all             0.0.0.0/0               ldap ldapserver=openldap ldapport=389 ldapbasedn="ou=database,dc=corp,dc=local" ldapbinddn="cn=admin,dc=corp,dc=local" ldapbindpasswd="12345678" ldapsearchattribute="uid"